export const adminApi = [
  "/designations",
  "/holidays",
  "/departments",
  "/schedule-types",
  "/leave-types",
  "/document-types",
  "/employees",
  "/applications?type=failure_to_log",
  "/applications?type=leave",
  "/applications?type=overtime",
  "/announcements",
  "/applications",
  "/attendances",
  "/trainings",
  "/schedules",
  "/applications?type=official_bussiness",
  "/payroll-comps",
  "/performances",
  "/payroll-periods",
  "/users/info",
  "/companies",
  "/loans",
  "/bank-accs",
  "/recruitments",
  "/assets",
  "/restrictions",
  "/payroll-lists",
];

export const employeeApi = [];
